import pygame

keyboard_row_with_numbers = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '=']
first_keyboard_row_with_letters = ['q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p']
second_keyboard_row_with_letters = ['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l']
third_keyboard_row_with_letters = ['z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '.']
all_keys = ['1' , '2', '3', '4', '5', '6', '7', '8', '9', '0', 'q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p', 'a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '.', 'Space', 'Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P', 'A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L', 'Z', 'X', 'C', 'V', 'B', 'N', 'M']
WIDTH = 1000
HEIGHT = 800
RED = (255, 0, 0)
BLUE = (30,144,255)
WHITE = (255, 255, 255)
GREEN = (155, 205, 150)
PINK = (252, 15, 192)
INTERV = 11
space_koord = 175
height_of_key = 25
indent_from_above = 15
circle_rad = 5
number_of_main_mistakes = 5
mistakes_left = 50
mistakes_interval = 55
keyboard_columns_interval = 25
above_left_and_right_indent = 90
symbols_per_sec_place = 110
left_indent = 45
exit_text_indent = 60
time_center = 90
one_minute = 60
milisec_in_sec = 1000
mainstr_height = HEIGHT/3
how_to_start_the_first_game_text_height = HEIGHT/3
keyboard_lower_indent = HEIGHT/5
exit_text_lower_indent = HEIGHT/8
error_text_height = HEIGHT/6
inval_text_height = HEIGHT/6
center_height = HEIGHT/2
center_width = WIDTH/2
mistakes_text_left = WIDTH/7
frame = 2
prev_window_with_statistic_and_heatmap_on_the_screen = 0
need_to_change_sentence = 1
user_is_typing_sentence = 2
only_keys_training_in_progress = -1
gm2_window_with_statistic_on_the_screen = -2
how_much_interv_we_need_to_leave_on_the_left_first_row = 1 
how_much_interv_we_need_to_leave_on_the_left_second_row = 2
how_much_interv_we_need_to_leave_on_the_left_third_row = 3
how_much_interv_we_need_to_leave_on_the_left_fourth_row = 4 
number_of_keyboard_rows = 5
devide_to_find_height_of_half_key = 2
first_keyboard_row_index = 0
second_keyboard_row_index = 1
third_keyboard_row_index = 2
fourth_keyboard_row_index = 3
shift_keyboard_row_index = 3
space_keyboard_row_index = 4
numbers_after_comma = 3
full_stop_code = 1102
comma_code = 1073
SPACE = "space"
LEFT_SHIFT = "LEFT SHIFT"
RIGHT_SHIFT = "RIGHT SHIFT"
CAPS_LOCK_ON = "CAPS LOCK"
CAPS_LOCK_OFF = "caps lock"
BIG_LEFT_ALT = "LEFT ALT"
SMALL_LEFT_ALT = "left alt"
RESET_STATISTICS_IN_FILE = "0 0 0 {}"
pygame.init()
big_font = pygame.font.SysFont('arial', 60)
average_font = pygame.font.SysFont('arial', 25)
small_font = pygame.font.SysFont('arial', 40)
exit_text = small_font.render("Press ESC to exit", 1, WHITE)