import pygame

key_brd0 = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '=']
key_brd1 = ['q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p']
key_brd2 = ['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l']
key_brd3 = ['z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '.']
keys_arr = ['1' , '2', '3', '4', '5', '6', '7', '8', '9', '0', 'q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p', 'a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '.', 'Space', 'Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P', 'A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L', 'Z', 'X', 'C', 'V', 'B', 'N', 'M']
WIDTH = 1000
HEIGHT = 800
Red = (255, 0, 0)
Blue = (30,144,255)
White = (255, 255, 255)
Green = (155, 205, 150)
Pink = (252, 15, 192)
interv = 11
sp_koord = 175
height_of_key = 25
indent_from_above = 15
circle_rad = 5
number_of_main_mistakes = 5
mistakes_left = 50
mistakes_interval = 55
keyboard_columns_interval = 25
above_left_and_right_indent = 90
symbols_per_sec_place = 110
left_indent = 45
exit_text_indent = 60
time_center = 90
one_minute = 60
milisec_in_sec = 1000
mainstr_height = HEIGHT/3
gm1_text_height = HEIGHT/3
keyboard_lower_indent = HEIGHT/5
exit_text_lower_indent = HEIGHT/8
error_text_height = HEIGHT/6
inval_text_height = HEIGHT/6
center_height = HEIGHT/2
center_width = WIDTH/2
mistakes_text_left = WIDTH/7
frame = 2
prev_window_with_statistic_and_heatmap_on_the_screen = 0
need_to_change_sentence = 1
user_is_typing_sentence = 2
only_keys_training_in_progress = -1
gm2_window_with_statistic_on_the_screen = -2
full_stop_code = 1102
comma_code = 1073
SPACE = "space"
pygame.init()
big_font = pygame.font.SysFont('arial', 60)
average_font = pygame.font.SysFont('arial', 25)
small_font = pygame.font.SysFont('arial', 40)
exit_text = small_font.render("Press ESC to exit", 1, White)